baseURL = "https://www.lkk7.com/notes"
title = "My notes"

theme = "fuji"
hasCJKLanguage = false
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
languageCode = "en"
defaultContentLanguage = "en"
summaryLength = 100
paginate = 10

[outputFormats]
  [outputFormats.SearchIndex]
    isPlainText = true
    notAlternative = true
    mediaType = "application/json"
    path = "/search/"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
  post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "Łukasz Łapiński"
  subTitle = "A minimal Hugo theme."
  defaultTheme = "dark"
  sourceURL = "https://github.com/lkk7/notes"
  showWordCounter = true
  showReadTime = false
  showLicenseInFooter = false
  showLicense = false
  showToc = false
  copyrightStartYear = "2020"

  description = "Notes made by lkk7 (Łukasz Łapiński) in form of a blog"
  og = "/img/og.png" # This will use the image called og.png in static/img folder
  mainSections = ["post"]

  # custom lazyload placeholder
  # 16:9
  lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"
  # Let images display in full brightness under dark mode
  # disableDarkImage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = false

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home (notes)"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About me"
    url = "https://www.lkk7.com"
    weight = 2
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 3
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
